version: '3'
services:
  mysql:
    image: mysql:5.7.25
    container_name: jdbc-file-blog-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: jdbc-file-blog
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: rootpw
    expose:
      - 3306

  kafka-broker:
    image: confluentinc/cp-kafka:5.3.1
    container_name: jdbc-file-blog-kafka
    ports:
      - "9092:9092"
    expose:
      - "9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=kafka-broker
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.1
    container_name: jdbc-file-blog-kafka-zookeeper
    ports:
      - "2181:2181"
    expose:
      - "2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
